version: "3.5"

services:
  server:
    image: webzio/duplicateservice:${TAG}
    hostname: '{{.Node.Hostname}}'
    ports:
      - 9039:9039
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/omgili/log/:/home/omgili/log/
    user: 1000:1000
    command: python server.py
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s

  consumer:
    image: webzio/duplicateservice:${TAG}
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/omgili/log/:/home/omgili/log/
    user: 1000:1000
    command: python RabbitMQ/consumer.py
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 15s
    depends_on:
      - server
    networks:
      - duplicate

networks:
  duplicate:
    external: true
    name: "host"
